package Vista;

import Controlador.ControllerVehiculos;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class FrmAgg_Vehiculos extends javax.swing.JFrame {

    int idvehiculo;
    int idpersonal;
//constructor que se utiliza cuando se va a actualizar algún datos sobre los vehiculos
    public FrmAgg_Vehiculos(int pidvehiculo) {
        initComponents();
        idvehiculo = pidvehiculo;
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);

        setIconImage(Logo());

        txtIDPersonal.setText(String.valueOf(ValidacionesSistema.Parametros_Vehiculos.getIdPersonal()));
        txtID.setVisible(false);
        txtIDPersonal.setVisible(false);

        txtID.setText(String.valueOf(ValidacionesSistema.Parametros_Vehiculos.getIdvehiculo()));
        txtIDPersonal.setText(String.valueOf(ValidacionesSistema.Parametros_Vehiculos.getIdPersonal()));
        idpersonal = ValidacionesSistema.Parametros_Vehiculos.getIdPersonal();
        System.out.println(idpersonal);
        System.out.println(ValidacionesSistema.Parametros_Vehiculos.getIdPersonal());
        txtPlaca.setText(ValidacionesSistema.Parametros_Vehiculos.getPlaca());
        txtColor.setText(ValidacionesSistema.Parametros_Vehiculos.getColor());

        btnConfirmar.setVisible(false);
        btnConfirmar_C.setVisible(true);
    }
//constructor que se utiliza para cuando se va a agregar un vehiculo
    FrmAgg_Vehiculos() {
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        btnConfirmar.setVisible(true);
        btnConfirmar_C.setVisible(false);

        txtIDPersonal.setText(String.valueOf(ValidacionesSistema.Parametros_Vehiculos.getIdPersonal()));

        txtID.setVisible(false);
        txtIDPersonal.setVisible(false);
    }

    public Image Logo() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        txtPlaca = new Controles_Personalizados.textfields.TextField();
        txtColor = new Controles_Personalizados.textfields.TextField();
        jLabel1 = new javax.swing.JLabel();
        btnConfirmar = new Controles_Personalizados.Botones.ButtonGradient();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnConfirmar_C = new Controles_Personalizados.Botones.ButtonGradient();
        txtID = new javax.swing.JTextField();
        txtIDPersonal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1099, 578));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(58, 50, 75));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPlaca.setBackground(new java.awt.Color(58, 50, 75));
        txtPlaca.setForeground(new java.awt.Color(253, 255, 254));
        txtPlaca.setCaretColor(new java.awt.Color(253, 255, 254));
        txtPlaca.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtPlaca.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtPlaca.setLabelText("Placa - Vehiculo");
        txtPlaca.setLineColor(new java.awt.Color(253, 255, 254));
        txtPlaca.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtPlaca.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 310, 70));

        txtColor.setBackground(new java.awt.Color(58, 50, 75));
        txtColor.setForeground(new java.awt.Color(253, 255, 254));
        txtColor.setCaretColor(new java.awt.Color(253, 255, 254));
        txtColor.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        txtColor.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtColor.setLabelText("Color - Vehiculo");
        txtColor.setLineColor(new java.awt.Color(253, 255, 254));
        txtColor.setSelectedTextColor(new java.awt.Color(58, 50, 75));
        txtColor.setSelectionColor(new java.awt.Color(253, 255, 254));
        panelRound1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Car.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 390));

        btnConfirmar.setBackground(new java.awt.Color(42, 36, 56));
        btnConfirmar.setForeground(new java.awt.Color(58, 50, 75));
        btnConfirmar.setText("Continuar");
        btnConfirmar.setColor1(new java.awt.Color(253, 255, 254));
        btnConfirmar.setColor2(new java.awt.Color(253, 255, 254));
        btnConfirmar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmarMouseClicked(evt);
            }
        });
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        panelRound1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 150, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelRound1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        btnConfirmar_C.setBackground(new java.awt.Color(42, 36, 56));
        btnConfirmar_C.setForeground(new java.awt.Color(58, 50, 75));
        btnConfirmar_C.setText("Continuar");
        btnConfirmar_C.setColor1(new java.awt.Color(253, 255, 254));
        btnConfirmar_C.setColor2(new java.awt.Color(253, 255, 254));
        btnConfirmar_C.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnConfirmar_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmar_CMouseClicked(evt);
            }
        });
        btnConfirmar_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmar_CActionPerformed(evt);
            }
        });
        panelRound1.add(btnConfirmar_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 150, -1));

        txtID.setText("id");
        panelRound1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        txtIDPersonal.setText("idp");
        panelRound1.add(txtIDPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        getContentPane().add(panelRound1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ControllerVehiculos objVehiculos = new ControllerVehiculos();

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        GuardarVehiculo();
        this.dispose();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        this.dispose();
        PanelOpcionesPersonal.showinter = 0;
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void btnConfirmar_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmar_CActionPerformed
        ActualizarVehiculo();
        this.dispose();
    }//GEN-LAST:event_btnConfirmar_CActionPerformed

    private void btnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmarMouseClicked
        GuardarVehiculo();
    }//GEN-LAST:event_btnConfirmarMouseClicked

    private void btnConfirmar_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmar_CMouseClicked
        ActualizarVehiculo();
    }//GEN-LAST:event_btnConfirmar_CMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    void GuardarVehiculo() {
        if (txtPlaca.getText().trim().isEmpty() || txtColor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Existen campos vacios, favor llenarlos todos", "Campos vacios", JOptionPane.WARNING_MESSAGE);
        } else {
            ControllerVehiculos.idPersonal = Integer.parseInt(txtIDPersonal.getText());
            ControllerVehiculos.placa = txtPlaca.getText();
            ControllerVehiculos.color = txtColor.getText();
            if (ControllerVehiculos.RegistrarVehiculo_Controller() == true) {
                JOptionPane.showMessageDialog(this, "Vehiculo registrado con exito", "Proceso de registro", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Vehiculo no fue registrado", "Proceso de registro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    void ActualizarVehiculo() {
        ControllerVehiculos.idvehiculo = idvehiculo;
        ControllerVehiculos.placa = txtPlaca.getText();
        ControllerVehiculos.color = txtColor.getText();
        ControllerVehiculos.idPersonal = idpersonal;
        System.out.println(idpersonal);
        if (ControllerVehiculos.ActualizarVehiculo_Controller() == true) {
            JOptionPane.showMessageDialog(this, "Vehiculo actualizado con exito", "Proceso de actualizacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Vehiculo no fue actualizado", "Proceso de actualizacion", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgg_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAgg_Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnConfirmar;
    private Controles_Personalizados.Botones.ButtonGradient btnConfirmar_C;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel jLabel1;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    private Controles_Personalizados.textfields.TextField txtColor;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDPersonal;
    private Controles_Personalizados.textfields.TextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
