/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerAccesos;
import Controles_Personalizados.RenderTable;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FrmBarcode_Entry extends javax.swing.JFrame {

    private String CapCarnet;
    DefaultTableModel tablemodel;
    private int idPersonal;

    /**
     * Creates new form FrmBarcode_Entry
     */
    public FrmBarcode_Entry() {
        initComponents();
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        String[] header = {"IDAcceso", "IDPersonal", "Carnet", "Fecha", "IDTipoAcceso", "Hora", "Acceso"};
        tablemodel = new DefaultTableModel(null, header);
        loadTable();
        TbEntryAccess.setDefaultRenderer(Object.class, new RenderTable());
        TbEntryAccess.setModel(tablemodel);
        TbEntryAccess.removeColumn(TbEntryAccess.getColumnModel().getColumn(0));
        TbEntryAccess.removeColumn(TbEntryAccess.getColumnModel().getColumn(0));
        TbEntryAccess.removeColumn(TbEntryAccess.getColumnModel().getColumn(2));
        this.setIconImage(Logo());
    }

    void loadTable() {
        ResultSet rs;
        try {
            while (tablemodel.getRowCount() > 0) {
                tablemodel.removeRow(0);
            }
            rs = ControllerAccesos.getdataEntry("vwAccesos");
            while (rs.next()) {
                Object[] data = {rs.getInt("idAcceso"), rs.getInt("idPersonal"), rs.getString("Carnet"), rs.getDate("fecha"), rs.getInt("idTipoAcceso"), rs.getTime("hora"), rs.getString("tipo_acceso")};
                tablemodel.addRow(data);
            }
        } catch (SQLException e) {
            System.out.println("Error:" + e.toString());
        }
    }

    public Image Logo() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
        return retvalue;
    }

    void insertbyCode128() {
        Date today = new Date();
        today.getTime();

        SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formatHour = new SimpleDateFormat("hh:mm:ss");
        String date = formatDate.format(today);
        String hour = formatHour.format(today);

        ControllerAccesos.setDate(date);
        ControllerAccesos.setHour(hour);
        ControllerAccesos.setID(idPersonal);
        ControllerAccesos.setTypeAccess(1);
        ControllerAccesos.setJustification("Sin justificar");
        if (ControllerAccesos.insertAccess() == true) {
            JOptionPane.showMessageDialog(null, "Su insercion se ha realizado");
        } else {
            JOptionPane.showMessageDialog(null, "No se realizo la insercion");
        }
    }

    void LookingForPersonal() {
        try {
            ControllerAccesos.setCarnet(CapCarnet);
            ResultSet rs = ControllerAccesos.LookiingForPersonal();
            if (rs.next()) {
                idPersonal = rs.getInt("idPersonal");
                System.out.println("Si se encontro, Su id es: " + idPersonal);
                insertbyCode128();
                TxtValidateBarcode.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "El codigo del Carné no esta registrado en el sistema", "Codigo no encontrado", JOptionPane.ERROR_MESSAGE);
                TxtValidateBarcode.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelAccesos.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("No se encontro");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbEntryAccess = new Controles_Personalizados.Tables.Table();
        TxtValidateBarcode = new Controles_Personalizados.textfields.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 580));
        setUndecorated(true);

        panelRound1.setBackground(new java.awt.Color(58, 50, 75));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbEntryAccess.setBackground(new java.awt.Color(231, 234, 239));
        TbEntryAccess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbEntryAccess.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TbEntryAccess.setGridColor(new java.awt.Color(58, 50, 75));
        TbEntryAccess.setSelectionBackground(new java.awt.Color(58, 50, 75));
        jScrollPane1.setViewportView(TbEntryAccess);

        panelRound1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 990, 320));

        TxtValidateBarcode.setBackground(new java.awt.Color(58, 50, 75));
        TxtValidateBarcode.setForeground(new java.awt.Color(254, 254, 254));
        TxtValidateBarcode.setCaretColor(new java.awt.Color(253, 255, 254));
        TxtValidateBarcode.setDisabledTextColor(new java.awt.Color(253, 255, 254));
        TxtValidateBarcode.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TxtValidateBarcode.setLabelText("Carnè");
        TxtValidateBarcode.setLineColor(new java.awt.Color(253, 255, 254));
        TxtValidateBarcode.setSelectionColor(new java.awt.Color(253, 255, 254));
        TxtValidateBarcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtValidateBarcodeMouseClicked(evt);
            }
        });
        TxtValidateBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValidateBarcodeActionPerformed(evt);
            }
        });
        panelRound1.add(TxtValidateBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 610, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 255, 254));
        jLabel3.setText("Entrada");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        getContentPane().add(panelRound1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void TxtValidateBarcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtValidateBarcodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValidateBarcodeMouseClicked

    private void TxtValidateBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValidateBarcodeActionPerformed
        // TODO add your handling code here:
        CapCarnet = TxtValidateBarcode.getText();
        LookingForPersonal();
        loadTable();
    }//GEN-LAST:event_TxtValidateBarcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarcode_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarcode_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarcode_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarcode_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarcode_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Tables.Table TbEntryAccess;
    private Controles_Personalizados.textfields.TextField TxtValidateBarcode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
