/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerCarnets;
import Controles_Personalizados.Botones.UWPButton;
import Controles_Personalizados.RenderTable;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.YearMonth;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferna
 */
public class FrmPersonalSinCarnet extends javax.swing.JFrame {

    private DefaultTableModel model;
    private final UWPButton BtnCarnet = new UWPButton();
    private ControllerCarnets objController = new ControllerCarnets();
    private int ID;
    public Font font = new Font("Roboto Black", Font.PLAIN, 18);
    private ImageIcon modifIcon = new ImageIcon(getClass().getResource("/Recursos_Proyecto/IDcarnet.png"));
    private String nombres;
    private String apellidos;
    private String imprimirid;
    private String Carnet;
    private String capnom;
    private String capapelli;

    /**
     * Creates new form FrmAgg_Carnets
     */
    public FrmPersonalSinCarnet() {
        initComponents();
        String[] Titulos = {"idPersonal", "Nombre", "Apellido", "Tipo Personal", "Documento", "Carné"};
        model = new DefaultTableModel(null, Titulos);
        TbPersonalSC.setModel(model);
        TbPersonalSC.setDefaultRenderer(Object.class, new RenderTable());
        BtnCarnet.setBackground(new Color(231, 235, 239));
        BtnCarnet.setIcon(modifIcon);
        BtnCarnet.setForeground(new Color(58, 50, 75));
        BtnCarnet.setFont(font);
        //TbPersonalSC.removeColumn(TbPersonalSC.getColumnModel().getColumn(4));
        BtnCarnet.setText("Generar");
        TbPersonalSC.removeColumn(TbPersonalSC.getColumnModel().getColumn(0));
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        setIconImage(Logo());
        cargarTabla();
    }

    public Image Logo() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
        return retvalue;
    }

    void carnet() {
        try {
            String id = String.valueOf(ID);
            if (id.length() > 0 && id.length() < 2) {
                imprimirid = String.valueOf("000" + id);
            } else if (id.length() == 2 && id.length() < 3) {
                imprimirid = String.valueOf("00" + id);
            } else if (id.length() == 3 && id.length() < 4) {
                imprimirid = String.valueOf("0" + id);
            } else if (id.length() == 4 && id.length() < 5) {
                imprimirid = String.valueOf(id);
            }
            int year = YearMonth.now().getYear();
            char firstl = capapelli.charAt(0);
            char firstn = capnom.charAt(0);
            nombres = String.valueOf(firstn);
            apellidos = String.valueOf(firstl);
            String carnetlocal = nombres + apellidos;
            String carnetlocal2 = year + imprimirid;
            String numerocarnet = carnetlocal + carnetlocal2;
            Carnet = numerocarnet;
            objController.setCarnet(Carnet);
            objController.setIdPersonal(ID);
            if (objController.IngresarCarnet() == true) {
                JOptionPane.showMessageDialog(null, "Proceso completado", "Carnet Agregado", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("Error interno" + e.toString());
        }
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        PanelTabla = new javax.swing.JScrollPane();
        TbPersonalSC = new Controles_Personalizados.Tables.Table();
        ScrollTabla = new Controles_Personalizados.ScrollBar.ScrollBarCustom();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        lblVehiculos1 = new javax.swing.JLabel();
        BtnGenerarTodos = new Controles_Personalizados.Botones.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(58, 50, 75));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTabla.setHorizontalScrollBar(null);
        PanelTabla.setVerticalScrollBar(ScrollTabla);
        PanelTabla.setWheelScrollingEnabled(false);

        TbPersonalSC.setBackground(new java.awt.Color(231, 234, 239));
        TbPersonalSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRES", "APELLIDOS", "TIPO DE PERSONAL", "ACCIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbPersonalSC.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TbPersonalSC.setGridColor(new java.awt.Color(58, 50, 75));
        TbPersonalSC.setName(""); // NOI18N
        TbPersonalSC.setSelectionBackground(new java.awt.Color(58, 50, 75));
        TbPersonalSC.setShowVerticalLines(false);
        TbPersonalSC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPersonalSCMouseClicked(evt);
            }
        });
        PanelTabla.setViewportView(TbPersonalSC);

        panelRound1.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 980, 460));

        ScrollTabla.setBackground(new java.awt.Color(58, 50, 75));
        ScrollTabla.setForeground(new java.awt.Color(58, 50, 75));
        panelRound1.add(ScrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1238, 177, 10, 40));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelRound1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, -1, -1));

        lblVehiculos1.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        lblVehiculos1.setForeground(new java.awt.Color(253, 255, 254));
        lblVehiculos1.setText("PERSONAL SIN CARNET");
        panelRound1.add(lblVehiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        BtnGenerarTodos.setBackground(new java.awt.Color(253, 255, 254));
        BtnGenerarTodos.setForeground(new java.awt.Color(58, 50, 75));
        BtnGenerarTodos.setText("Generar todos");
        BtnGenerarTodos.setColor1(new java.awt.Color(253, 255, 254));
        BtnGenerarTodos.setColor2(new java.awt.Color(253, 255, 254));
        BtnGenerarTodos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnGenerarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarTodosActionPerformed(evt);
            }
        });
        panelRound1.add(BtnGenerarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 180, 40));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    FrmAgg_Carnet add = new FrmAgg_Carnet();

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        PanelOpcionesPersonal.showinter = 0;
        this.dispose();
        add.dispose();
    }//GEN-LAST:event_btnCerrarMousePressed
    void cargarTabla() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        try {
            ResultSet rs = objController.SinCarnetController();
            while (rs.next()) {
                Object[] Valores = {rs.getInt("idPersonal"), rs.getString("nombre_p"), rs.getString("apellido_p"), rs.getString("tipo_personal"), rs.getString("documento"), BtnCarnet};
                model.addRow(Valores);
            }
        } catch (SQLException e) {
            System.out.println("Error al cargar, Error de vista" + e.toString());
        }
    }
    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void TbPersonalSCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPersonalSCMouseClicked
        // TODO add your handling code here:
        int column = TbPersonalSC.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / TbPersonalSC.getRowHeight();
        BtnCarnet.setName("BtnCarnet");
        if (evt.getClickCount() == 1) {
            JTable rcp = (JTable) evt.getSource();
            ID = (int) rcp.getModel().getValueAt(rcp.getSelectedRow(), 0);
            capnom = rcp.getModel().getValueAt(rcp.getSelectedRow(), 1).toString();
            capapelli = rcp.getModel().getValueAt(rcp.getSelectedRow(), 2).toString();
        }
        if (row < TbPersonalSC.getRowCount() || row >= 0 || column < TbPersonalSC.getColumnCount() || column >= 0) {
            Object vals = TbPersonalSC.getValueAt(row, column);
            if (vals instanceof UWPButton) {
                ((UWPButton) vals).doClick(); // aqui esta
                UWPButton btns = (UWPButton) vals;
                if (btns.getName().equals("BtnCarnet")) {
                    int confirmacion = JOptionPane.YES_NO_OPTION;
                    int a = JOptionPane.showConfirmDialog(null, "¿Desea generar el Carné de: " + capnom + " " + capapelli + "?", "Generar Carné", confirmacion, JOptionPane.QUESTION_MESSAGE);
                    if (a == 0) {
                        carnet();
                    }

                }
            }
        }
    }//GEN-LAST:event_TbPersonalSCMouseClicked

    private void BtnGenerarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarTodosActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.YES_NO_OPTION;
        int a = JOptionPane.showConfirmDialog(null, "¿Desea generar el carné de todo el personal que no tiene uno?", "Generar Carné", confirmacion, JOptionPane.QUESTION_MESSAGE);
        if (a == 0) {
            Date date = new Date();
            SimpleDateFormat getYearFormat = new SimpleDateFormat("yyyy");
            String currentYear = getYearFormat.format(date);
            
            objController.setAño(currentYear);
            boolean respuesta = objController.GenerarCarnetsTodos();
            if(respuesta == true){
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso completado", "Carnés generados exitosamente", 1);
            }else{
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso fallido", "Los carnés no pudieron ser generados", 3);
            }
            cargarTabla();
            this.dispose();
        }
    }//GEN-LAST:event_BtnGenerarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalSinCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalSinCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalSinCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalSinCarnet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonalSinCarnet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Botones.ButtonGradient BtnGenerarTodos;
    private javax.swing.JScrollPane PanelTabla;
    private Controles_Personalizados.ScrollBar.ScrollBarCustom ScrollTabla;
    private Controles_Personalizados.Tables.Table TbPersonalSC;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel lblVehiculos1;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
