/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerP_U_Usuarios;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danlo
 */
public class FrmRestablecimiento extends javax.swing.JFrame {

    public String user;

    public FrmRestablecimiento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Creates new form FrmRestablecimiento
     */
    public FrmRestablecimiento(String usuario) {
        initComponents();
        this.setTitle("Restablecimiento de contraseña");
        TxtPass.setEchoChar('•');
        TxtConfir.setEchoChar('•');
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        setIconImage(Logo());
        user = usuario;
    }

    public Image Logo() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
        return retvalue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        panelRound2 = new Controles_Personalizados.Paneles.PanelRound();
        ImagenRecuBio = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        btnRestablecer = new Controles_Personalizados.Botones.ButtonGradient();
        TxtPass = new Controles_Personalizados.textfields.PasswordField();
        TxtConfir = new Controles_Personalizados.textfields.PasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(42, 36, 56));
        panelRound1.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(254, 254, 254));
        panelRound2.setPreferredSize(new java.awt.Dimension(698, 768));
        panelRound2.setRoundBottomLeft(35);
        panelRound2.setRoundTopLeft(35);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenRecuBio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/ResetImg.png"))); // NOI18N
        panelRound2.add(ImagenRecuBio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-left-arrow-circle 1.png"))); // NOI18N
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBackMouseClicked(evt);
            }
        });
        panelRound2.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        panelRound1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        panelRound1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        lblText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/RestableceContraText.png"))); // NOI18N
        panelRound1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        btnRestablecer.setForeground(new java.awt.Color(42, 36, 56));
        btnRestablecer.setText("Confirmar y Cambiar");
        btnRestablecer.setColor1(new java.awt.Color(254, 254, 254));
        btnRestablecer.setColor2(new java.awt.Color(254, 254, 254));
        btnRestablecer.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });
        panelRound1.add(btnRestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 310, -1));

        TxtPass.setBackground(new java.awt.Color(42, 36, 56));
        TxtPass.setForeground(new java.awt.Color(254, 254, 254));
        TxtPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TxtPass.setLabelText("Contraseña");
        TxtPass.setLineColor(new java.awt.Color(187, 187, 187));
        TxtPass.setShowAndHide(true);
        TxtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPassKeyTyped(evt);
            }
        });
        panelRound1.add(TxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 420, 70));

        TxtConfir.setBackground(new java.awt.Color(42, 36, 56));
        TxtConfir.setForeground(new java.awt.Color(254, 254, 254));
        TxtConfir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TxtConfir.setLabelText("Confirmar Contraseña");
        TxtConfir.setLineColor(new java.awt.Color(187, 187, 187));
        TxtConfir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtConfirKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtConfirKeyTyped(evt);
            }
        });
        panelRound1.add(TxtConfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 420, 70));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed
    void CambiarClave() {
        if(! TxtPass.getText().equals("") || ! TxtConfir.getText().equals("")){
            if (Objects.equals(TxtPass.getText(), TxtConfir.getText())) {
                ControllerP_U_Usuarios cc = new ControllerP_U_Usuarios();
                cc.setUsuario(user);
                cc.setClave(ValidacionesSistema.ValidacionesBeep_Go.EncriptarContra(TxtConfir.getText()));
                if (cc.CambiandoClave() == true) {
                    JOptionPane.showMessageDialog(null, "Su contraseña ha sido agregada");
                    FrmLogin iniciar = new FrmLogin();
                    iniciar.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR AL REALIZAR EL PROCESO");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las claves ingresadas deden de ser las mismas", "Contraseña incorrecta", JOptionPane.WARNING_MESSAGE);

            }
        }else{
            JOptionPane.showMessageDialog(null, "Campos vacios", "Existen campos vacios", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void btnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseClicked
        // TODO add your handling code here:
        FrmLogin men = new FrmLogin();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoBackMouseClicked

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        // TODO add your handling code here:
        CambiarClave();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    private void TxtPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPassKeyTyped
        // TODO add your handling code here:
        if (TxtPass.getText().length() >= 30) {
            evt.consume();
        } else {
            ValidacionesSistema.ValidacionesBeep_Go.SinEspacios(evt);
        }
    }//GEN-LAST:event_TxtPassKeyTyped

    private void TxtConfirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtConfirKeyTyped
        // TODO add your handling code here:
        if (TxtConfir.getText().length() >= 30) {
            evt.consume();
        } else {
            ValidacionesSistema.ValidacionesBeep_Go.SinEspacios(evt);
        }
    }//GEN-LAST:event_TxtConfirKeyTyped

    private void TxtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPassKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && TxtPass.getText().equals("") && ! TxtConfir.getText().equals("")) {
            CambiarClave();
        }else if (evt.isControlDown() || evt.isShiftDown())
        {
            evt.consume();
        }
    }//GEN-LAST:event_TxtPassKeyPressed

    private void TxtConfirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtConfirKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && ! TxtPass.getText().equals("") && ! TxtConfir.getText().equals("")) {
            CambiarClave();
        }else if (evt.isControlDown() || evt.isShiftDown())
        {
            evt.consume();
        }
    }//GEN-LAST:event_TxtConfirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRestablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRestablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRestablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRestablecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRestablecimiento dialog = new FrmRestablecimiento();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenRecuBio;
    private Controles_Personalizados.textfields.PasswordField TxtConfir;
    private Controles_Personalizados.textfields.PasswordField TxtPass;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnGoBack;
    private javax.swing.JLabel btnMinimizar;
    private Controles_Personalizados.Botones.ButtonGradient btnRestablecer;
    private javax.swing.JLabel lblText;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    private Controles_Personalizados.Paneles.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
