/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerParqueo;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import Controles_Personalizados.Botones.UWPButton;
import Controles_Personalizados.RenderTable;
import Controles_Personalizados.Tables.Table;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import java.awt.Font;
import java.security.spec.RSAPrivateCrtKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author danlo
 */
public class PanelParqueo extends javax.swing.JPanel {

    private final UWPButton btnupdate = new UWPButton();
    private final UWPButton btndelete = new UWPButton();
    private final ImageIcon modifIcon = new ImageIcon(getClass().getResource("/Recursos_Proyecto/editar.png"));
    private final ImageIcon deleteIcon = new ImageIcon(getClass().getResource("/Recursos_Proyecto/eliminar.png"));
    private int frmstate = 1;
    public Font font = new Font("Roboto Black", Font.PLAIN, 18);

    /**
     * Creates new form PanelParqueo
     */
    public PanelParqueo() {
        initComponents();
        String[] headerpark = {"IDDetalle", "IDPersonal", "Carnet", "IDAcceso", "Fecha", "Hora", "IDVehiculo", "Placa", "IDEstacionamiento", "Estacionamiento", "IDParqueo", "Parqueo", "Ubicación", "Modificar", "Eliminar"};
        tbpark = new DefaultTableModel(null, headerpark);
        TbParqueosWhite.setModel(tbpark);

        getdataPark();

        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(0));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(0));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(1));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(3));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(4));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(5));

        TbParqueosWhite.getColumnModel().getColumn(4).setPreferredWidth(100);//9

        TbParqueosWhite.setDefaultRenderer(Object.class, new RenderTable());
        TbParqueosWhite.setFont(ValidacionesSistema.ValidacionesBeep_Go.font);
        btndelete.setBackground(new Color(231, 234, 239));
        btnupdate.setBackground(new Color(231, 234, 239));
        btndelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnupdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btndelete.setIcon(deleteIcon);
        btnupdate.setIcon(modifIcon);
        btnupdate.setName("btnModificar");
        btndelete.setName("btnEliminar");
    }

    final void refresh() {
        if (frmstate == 1 && !(park.isActive())) {
            getdataPark();
            frmstate = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRound1 = new Controles_Personalizados.Paneles.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblParqueo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnFiltrar = new Controles_Personalizados.Botones.UWPButton();
        btnAgregar = new Controles_Personalizados.Botones.UWPButton();
        btnInforme = new Controles_Personalizados.Botones.UWPButton();
        jPanel3 = new javax.swing.JPanel();
        scrollBarCustom1 = new Controles_Personalizados.ScrollBar.ScrollBarCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbParqueosWhite = new Controles_Personalizados.Tables.Table();

        setBackground(new java.awt.Color(42, 36, 56));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        panelRound1.setBackground(new java.awt.Color(231, 234, 239));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(231, 234, 239));
        jPanel2.setMinimumSize(new java.awt.Dimension(1240, 135));
        jPanel2.setPreferredSize(new java.awt.Dimension(1240, 135));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(231, 234, 239));
        jPanel4.setPreferredSize(new java.awt.Dimension(1240, 75));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblParqueo.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        lblParqueo.setForeground(new java.awt.Color(58, 50, 75));
        lblParqueo.setText("Parqueos");
        jPanel4.add(lblParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(231, 234, 239));
        jPanel5.setPreferredSize(new java.awt.Dimension(1240, 70));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFiltrar.setBackground(new java.awt.Color(58, 50, 75));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Filtrar Blanco.png"))); // NOI18N
        btnFiltrar.setText(" Filtrar");
        btnFiltrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 150, 40));

        btnAgregar.setBackground(new java.awt.Color(58, 50, 75));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Agregar Blanco.png"))); // NOI18N
        btnAgregar.setText(" Agregar");
        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        jPanel5.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        btnInforme.setBackground(new java.awt.Color(58, 50, 75));
        btnInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-file-doc-white.png"))); // NOI18N
        btnInforme.setText("Informe");
        btnInforme.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnInforme.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnInforme.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformeMouseClicked(evt);
            }
        });
        jPanel5.add(btnInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 40));

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(231, 234, 239));
        jPanel3.setPreferredSize(new java.awt.Dimension(461, 403));
        jPanel3.setLayout(new java.awt.BorderLayout());

        scrollBarCustom1.setBackground(new java.awt.Color(58, 50, 75));
        scrollBarCustom1.setForeground(new java.awt.Color(58, 50, 75));
        jPanel3.add(scrollBarCustom1, java.awt.BorderLayout.EAST);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(15, 26));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(461, 403));
        jScrollPane1.setVerticalScrollBar(scrollBarCustom1);

        TbParqueosWhite = new Controles_Personalizados.Tables.Table(){

            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TbParqueosWhite.setBackground(new java.awt.Color(231, 234, 239));
        TbParqueosWhite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TbParqueosWhite.setGridColor(new java.awt.Color(58, 50, 75));
        TbParqueosWhite.setPreferredSize(new java.awt.Dimension(450, 880));
        TbParqueosWhite.setSelectionBackground(new java.awt.Color(58, 50, 75));
        TbParqueosWhite.setShowVerticalLines(false);
        jScrollPane1.setViewportView(TbParqueosWhite);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 500;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 10, 15);
        panelRound1.add(jPanel1, gridBagConstraints);

        add(panelRound1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    FrmConfigPark park = new FrmConfigPark();
    DefaultTableModel tbpark;


    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        if (park.isShowing()) {
            park.setVisible(false);
        }
        park = new FrmConfigPark();
        park.setVisible(true);

    }//GEN-LAST:event_btnAgregarMouseClicked

    FrmSetPark setPark = new FrmSetPark();

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        getdataPark();
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        getdataPark();
    }//GEN-LAST:event_formComponentShown

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        refresh();
    }//GEN-LAST:event_formMouseReleased

    private void btnInformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformeMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnInformeMouseClicked

    public void getdataPark() {
        String tablename = "vwDetalle_Estacionamientos";
        while (tbpark.getRowCount() > 0) {
            tbpark.removeRow(0);
        }

        try {
            ResultSet rs = Controlador.ControllerAccesos.getdata(tablename);
            while (rs.next()) {
                Object[] data = {rs.getInt("IDDetalle"), rs.getInt("idPersonal"), rs.getString("carnet"), rs.getInt("idAcceso"), rs.getDate("fecha"), rs.getTime("hora"), rs.getInt("idVehiculo"), rs.getString("placa"), rs.getInt("idEstacionamiento"), rs.getInt("numero_estacionamiento"), rs.getInt("idParqueo"), rs.getInt("numero_parqueo"), rs.getString("Ubicacion"), btnupdate, btndelete};
                tbpark.addRow(data);
                //que recupere los datos q especifico con la columname y los guarde en un object
            }
        } catch (SQLException e) {
            System.out.println("Error view: " + e.toString());
        }

    }

    public void deletePark(int ID) {
        ControllerParqueo park = new ControllerParqueo();
        ControllerParqueo.setIDDetail(ID);
        System.out.println(ControllerParqueo.getIDDetail());
        if (ControllerParqueo.getIDDetail() > 0) {
            if (park.deletePark() == true) {
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso completado", "Usuario eliminado", 1);
                getdataPark();
            } else {
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso fallido", "Usuario no pudo ser eliminado", 2);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Tables.Table TbParqueosWhite;
    private Controles_Personalizados.Botones.UWPButton btnAgregar;
    private Controles_Personalizados.Botones.UWPButton btnFiltrar;
    private Controles_Personalizados.Botones.UWPButton btnInforme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblParqueo;
    private Controles_Personalizados.Paneles.PanelRound panelRound1;
    private Controles_Personalizados.ScrollBar.ScrollBarCustom scrollBarCustom1;
    // End of variables declaration//GEN-END:variables
}
