/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerParqueo;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import Controles_Personalizados.Botones.UWPButton;
import Controles_Personalizados.RenderTable;
import Controles_Personalizados.Tables.Table;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import java.awt.Font;
import java.security.spec.RSAPrivateCrtKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author danlo
 */
public class PanelParqueo extends javax.swing.JPanel {

    private final UWPButton btnupdate = new UWPButton();
    private final UWPButton btndelete = new UWPButton();
    private final ImageIcon modifIcon = new ImageIcon(getClass().getResource("/Recursos_Proyecto/editar.png"));
    private final ImageIcon deleteIcon = new ImageIcon(getClass().getResource("/Recursos_Proyecto/eliminar.png"));
    private int frmstate = 1;
    public Font font = new Font("Roboto Black", Font.PLAIN, 18);

    /**
     * Creates new form PanelParqueo
     */
    public PanelParqueo() {
        initComponents();
        String[] headerpark = {"IDDetalle", "IDPersonal", "Carnet", "IDAcceso", "Fecha","Hora", "IDVehiculo","Placa","IDEstacionamiento", "Estacionamiento","IDParqueo", "Parqueo", "Ubicación","Modificar", "Eliminar"};
        tbpark = new DefaultTableModel(null, headerpark);
        TbParqueosWhite.setModel(tbpark);
        
        getdataPark();
        
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(0));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(0));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(1));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(3));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(4));
        TbParqueosWhite.removeColumn(TbParqueosWhite.getColumnModel().getColumn(5));
        
        TbParqueosWhite.getColumnModel().getColumn(4).setPreferredWidth(100);//9
        
        TbParqueosWhite.setDefaultRenderer(Object.class, new RenderTable());
        
        btndelete.setBackground(new Color(231, 234, 239));
        btnupdate.setBackground(new Color(231, 234, 239));
        btndelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnupdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btndelete.setIcon(deleteIcon);
        btnupdate.setIcon(modifIcon);
        btnupdate.setName("btnModificar");
        btndelete.setName("btnEliminar");
    }

    final void refresh() {
        if (frmstate == 1 && !(park.isActive())) {
            getdataPark();
            frmstate = 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        lblParqueo = new javax.swing.JLabel();
        btnFiltrar = new Controles_Personalizados.Botones.UWPButton();
        btnAgregar = new Controles_Personalizados.Botones.UWPButton();
        PanelTabla = new javax.swing.JScrollPane();
        TbParqueosWhite = new Controles_Personalizados.Tables.Table();
        ScrollTabla = new Controles_Personalizados.ScrollBar.ScrollBarCustom();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(42, 36, 56));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelFondo.setBackground(new java.awt.Color(231, 234, 239));
        PanelFondo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PanelFondo.setPreferredSize(new java.awt.Dimension(1270, 620));
        PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblParqueo.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        lblParqueo.setForeground(new java.awt.Color(58, 50, 75));
        lblParqueo.setText("Parqueos");
        PanelFondo.add(lblParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnFiltrar.setBackground(new java.awt.Color(58, 50, 75));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Filtrar Blanco.png"))); // NOI18N
        btnFiltrar.setText(" Filtrar");
        btnFiltrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        PanelFondo.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, 40));

        btnAgregar.setBackground(new java.awt.Color(58, 50, 75));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Agregar Blanco.png"))); // NOI18N
        btnAgregar.setText(" Agregar");
        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        PanelFondo.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 40));

        PanelTabla.setHorizontalScrollBar(null);
        PanelTabla.setVerticalScrollBar(ScrollTabla);
        PanelTabla.setWheelScrollingEnabled(false);

        TbParqueosWhite = new Controles_Personalizados.Tables.Table(){

            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }

        };
        TbParqueosWhite.setBackground(new java.awt.Color(231, 234, 239));
        TbParqueosWhite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CARNET", "NOMBRES", "TIPO USUARIO", "%ENTRADAS", "%SALIDAS", "ACCIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbParqueosWhite.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TbParqueosWhite.setGridColor(new java.awt.Color(58, 50, 75));
        TbParqueosWhite.setName(""); // NOI18N
        TbParqueosWhite.setSelectionBackground(new java.awt.Color(58, 50, 75));
        TbParqueosWhite.setShowVerticalLines(false);
        TbParqueosWhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbParqueosWhiteMouseClicked(evt);
            }
        });
        PanelTabla.setViewportView(TbParqueosWhite);

        PanelFondo.add(PanelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1230, 480));

        ScrollTabla.setBackground(new java.awt.Color(58, 50, 75));
        ScrollTabla.setForeground(new java.awt.Color(58, 50, 75));
        PanelFondo.add(ScrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1238, 177, 10, 40));

        jPanel1.add(PanelFondo, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2formFocusGained(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2formComponentShown(evt);
            }
        });
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    FrmConfigPark park = new FrmConfigPark();
    DefaultTableModel tbpark;


    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        if (park.isShowing()) {
            park.setVisible(false);
        }
        park = new FrmConfigPark();
        park.setVisible(true);

    }//GEN-LAST:event_btnAgregarMouseClicked

    FrmSetPark setPark = new FrmSetPark();
    
    private void TbParqueosWhiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbParqueosWhiteMouseClicked
        Table tb = (Table) evt.getSource();//para obtener los datos de la fila

        int row = evt.getY() / TbParqueosWhite.getRowHeight();
        int col = TbParqueosWhite.getColumnModel().getColumnIndexAtX(evt.getX());
        try {
            if (row < TbParqueosWhite.getRowCount() && row >= 0 && col < TbParqueosWhite.getColumnCount() && col >= 0) {
                Object obj = TbParqueosWhite.getValueAt(row, col);
                if (obj instanceof UWPButton) {
                    ((UWPButton) obj).doClick();
                    UWPButton btn = (UWPButton) obj;
                    if (btn.getName().equals("btnModificar")) {
                        if (park.isShowing()) {
                            park.setVisible(false);

                        }
                        //envio el station que en el q se registro, para que se habilite y pueda cambiar el parqueo
                        park.setStation(Integer.valueOf(tb.getModel().getValueAt(tb.getSelectedRow(), 9).toString()));
                        park.setPark(tb.getModel().getValueAt(tb.getSelectedRow(), 11).toString());                        
                                                
                        
                        int ID = Integer.parseInt(tb.getModel().getValueAt(tb.getSelectedRow(), 0).toString());
                        FrmSetPark.setIDDetail(ID);
                        
                        int station = Integer.parseInt(tb.getModel().getValueAt(tb.getSelectedRow(), 8).toString());
                        ControllerParqueo.setNumberPark(station);
                        
                        park.setVisible(true);
                        frmstate = 1;
                        FrmSetPark.action = 1;

                    }
                    if (btn.getName().equals("btnEliminar")) {
                        int msg = JOptionPane.showConfirmDialog(this, "¿Desea eliminar este dato?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
                        if (msg == JOptionPane.YES_OPTION) {
                            deletePark(Integer.valueOf(tb.getModel().getValueAt(tb.getSelectedRow(), 0).toString()));
                        }
                    }
                }
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_TbParqueosWhiteMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        getdataPark();
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        getdataPark();
    }//GEN-LAST:event_formComponentShown

    private void jPanel2formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2formFocusGained

    private void jPanel2formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2formComponentShown

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        refresh();
    }//GEN-LAST:event_formMouseReleased

    public void getdataPark() {
        String tablename = "vwDetalle_Estacionamientos";
        if (tbpark.getRowCount() > 0) {//si hay columnas antes de cargar 
            tbpark.removeRow(0);      //borre las filas q tenía 
        } else {//si no hay filas
            try {
                ResultSet rs = Controlador.ControllerAccesos.getdata(tablename);
                while (rs.next()) {
                    Object[] data = {rs.getInt("IDDetalle"), rs.getInt("idPersonal"), rs.getString("carnet"), rs.getInt("idAcceso"), rs.getDate("fecha"), rs.getTime("hora"), rs.getInt("idVehiculo"), rs.getString("placa"), rs.getInt("idEstacionamiento"), rs.getInt("numero_estacionamiento"),rs.getInt("idParqueo"),rs.getInt("numero_parqueo") , rs.getString("Ubicacion"), btnupdate, btndelete};
                    tbpark.addRow(data);
                    //que recupere los datos q especifico con la columname y los guarde en un object
                }
            } catch (SQLException e) {
                System.out.println("Error view: " + e.toString());
            }

        }
    }

    public void deletePark(int ID) {
        ControllerParqueo park = new ControllerParqueo();
        park.setID(ID);
        if (park.getID() > 0) {
            if (park.deletePark() == true) {
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso completado", "Usuario eliminado", 1);
                getdataPark();
            } else {
                ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso fallido", "Usuario no pudo ser eliminado", 2);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private javax.swing.JScrollPane PanelTabla;
    private Controles_Personalizados.ScrollBar.ScrollBarCustom ScrollTabla;
    private Controles_Personalizados.Tables.Table TbParqueosWhite;
    private Controles_Personalizados.Botones.UWPButton btnAgregar;
    private Controles_Personalizados.Botones.UWPButton btnFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblParqueo;
    // End of variables declaration//GEN-END:variables
}
