/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerUsuarios;
import Controles_Personalizados.Botones.UWPButton;
import Controles_Personalizados.RenderTable;
import Controles_Personalizados.Tables.Renderer;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sun.reflect.generics.tree.CharSignature;

/**
 *
 * @author danlo
 */
public class PanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form FrmUsuarios
     */
    DefaultTableModel modelo;
    private final UWPButton btnActualizar = new UWPButton();
    private final UWPButton btnEliminar = new UWPButton();
    private Font font = new Font("Roboto Black", Font.PLAIN, 18);
    ImageIcon Modificar = new ImageIcon(getClass().getResource("/Recursos_Proyecto/editar.png"));
    ImageIcon Eliminar = new ImageIcon(getClass().getResource("/Recursos_Proyecto/eliminar.png"));
    FrmAgg_Usuarios agg = new FrmAgg_Usuarios();
    private int frmstate = 1;
    byte[] imagen;

    public PanelUsuarios() {
        initComponents();
        String[] TitulosTabla = {"ID", "idPersonal", "Nombres", "Apellidos", "Usuario", "idTipoUsuario", "Tipo de usuario", "idEstadoUsuario", "Estado del usuario", "Imagen", "Modificar", "Eliminar"};
        modelo = new DefaultTableModel(null, TitulosTabla) {
            @Override
            public boolean isCellEditable(int row, int column) { // aqui esta
                return false;
            }
        };
        tbUsuarios.setModel(modelo);
        tbUsuarios.setDefaultRenderer(Object.class, new RenderTable());
        CargarTabla();
        tbUsuarios.removeColumn(tbUsuarios.getColumnModel().getColumn(0));
        tbUsuarios.removeColumn(tbUsuarios.getColumnModel().getColumn(0));
        tbUsuarios.removeColumn(tbUsuarios.getColumnModel().getColumn(3));
        tbUsuarios.removeColumn(tbUsuarios.getColumnModel().getColumn(4));
        tbUsuarios.removeColumn(tbUsuarios.getColumnModel().getColumn(5));

    }

    final void refresh() {
        if (frmstate == 1 && !(agg.isActive())) {
            CargarTabla();
            frmstate = 0;
        }
    }

    public void CargarTabla() {
        ControllerUsuarios obj = new ControllerUsuarios();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        try {
            ResultSet rs = obj.CargarUsuarios_C();
            while (rs.next()) {
                btnActualizar.setIcon(Modificar);
                btnEliminar.setIcon(Eliminar);
                btnActualizar.setBackground(new Color(231, 234, 239));
                btnEliminar.setBackground(new Color(231, 234, 239));
                Object[] oValores = {rs.getInt("idUsuario"), rs.getInt("idPersonal"), rs.getString("nombre_p"), rs.getString("apellido_p"), rs.getString("nombre_usuario"), rs.getInt("idTipoUsuario"), rs.getString("tipo_usuario"), rs.getInt("idEstadoUsuario"), rs.getString("estado_usuario"), rs.getBytes("imagen"), btnActualizar, btnEliminar};

                modelo.addRow(oValores);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        jPanel1 = new javax.swing.JPanel();
        ScrollTabla = new Controles_Personalizados.ScrollBar.ScrollBarCustom();
        jPanel2 = new javax.swing.JPanel();
        PanelTabla = new javax.swing.JScrollPane();
        tbUsuarios = new Controles_Personalizados.Tables.Table();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnFiltrar = new Controles_Personalizados.Botones.UWPButton();
        btnAgregar = new Controles_Personalizados.Botones.UWPButton();
        lblUsuarios = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(42, 36, 56));
        setLayout(new java.awt.BorderLayout());

        PanelFondo.setBackground(new java.awt.Color(231, 234, 239));
        PanelFondo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        PanelFondo.setPreferredSize(new java.awt.Dimension(1270, 620));
        PanelFondo.setRoundBottomLeft(20);
        PanelFondo.setRoundBottomRight(20);
        PanelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelFondoMouseMoved(evt);
            }
        });
        PanelFondo.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(231, 234, 239));
        jPanel1.setLayout(new java.awt.BorderLayout());

        ScrollTabla.setBackground(new java.awt.Color(58, 50, 75));
        ScrollTabla.setForeground(new java.awt.Color(58, 50, 75));
        jPanel1.add(ScrollTabla, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(231, 234, 239));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelTabla.setHorizontalScrollBar(null);
        PanelTabla.setVerticalScrollBar(ScrollTabla);
        PanelTabla.setWheelScrollingEnabled(false);

        tbUsuarios.setBackground(new java.awt.Color(231, 234, 239));
        tbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CARNET", "NOMBRES", "TIPO USUARIO", "%ENTRADAS", "%SALIDAS", "ACCIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUsuarios.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tbUsuarios.setGridColor(new java.awt.Color(58, 50, 75));
        tbUsuarios.setName(""); // NOI18N
        tbUsuarios.setSelectionBackground(new java.awt.Color(58, 50, 75));
        tbUsuarios.setShowVerticalLines(false);
        tbUsuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseMoved(evt);
            }
        });
        tbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuariosMouseClicked(evt);
            }
        });
        PanelTabla.setViewportView(tbUsuarios);

        jPanel2.add(PanelTabla, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(231, 234, 239));
        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(231, 234, 239));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFiltrar.setBackground(new java.awt.Color(58, 50, 75));
        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Filtrar Blanco.png"))); // NOI18N
        btnFiltrar.setText(" Filtrar");
        btnFiltrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnFiltrar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel4.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 150, 40));

        btnAgregar.setBackground(new java.awt.Color(58, 50, 75));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Agregar Blanco.png"))); // NOI18N
        btnAgregar.setText(" Agregar");
        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 40));

        lblUsuarios.setFont(new java.awt.Font("Roboto Medium", 0, 40)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(58, 50, 75));
        lblUsuarios.setText("Usuarios");
        jPanel4.add(lblUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setBackground(new java.awt.Color(231, 234, 239));
        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        PanelFondo.add(jPanel1, gridBagConstraints);

        add(PanelFondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    /* btnModificar.setIcon(Modificar);
    btnEliminar.setIcon(Eliminar);
    btnModificar.setBackground(new Color(231,234,239));
    btnEliminar.setBackground(new Color(231,234,239)); */
    void CargarImagen() {
        ControllerUsuarios objc = new ControllerUsuarios(ValidacionesSistema.Parametros_Usuario.getID());
        ResultSet rs;
        rs = objc.BuscarImagen_C();
        try {
            if (rs.next()) {
                imagen = rs.getBytes("imagen");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        ValidacionesSistema.Parametros_Usuario.setTitulo("Agregar usuario");
        ValidacionesSistema.Parametros_Usuario.setBoton("Agregar");
        if (agg.isVisible()) {
            agg.toFront();

        } else {
            agg.setVisible(true);
        }
        frmstate = 1;
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseClicked
        // TODO add your handling code here:
        JTable tb = (JTable) evt.getSource();
        String nombre = null;
        int column = tbUsuarios.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbUsuarios.getRowHeight();
        btnActualizar.setName("btnActualizar");
        btnEliminar.setName("btnEliminar");
        if (evt.getClickCount() == 1) {
            JTable rcp = (JTable) evt.getSource();
            ValidacionesSistema.Parametros_Usuario.setID((int) rcp.getModel().getValueAt(rcp.getSelectedRow(), 0));
            ValidacionesSistema.Parametros_Usuario.setIdPersonal((int) rcp.getModel().getValueAt(rcp.getSelectedRow(), 1));
            ValidacionesSistema.Parametros_Usuario.setNombre_usuario(rcp.getModel().getValueAt(rcp.getSelectedRow(), 4).toString());
            ValidacionesSistema.Parametros_Usuario.setIdTipoUsuario((int) rcp.getModel().getValueAt(rcp.getSelectedRow(), 5));
            ValidacionesSistema.Parametros_Usuario.setIdEstadoUsuario((int) rcp.getModel().getValueAt(rcp.getSelectedRow(), 7));
            CargarImagen();
            ValidacionesSistema.Parametros_Usuario.setImagen(imagen);
        }

        if (row < tbUsuarios.getRowCount() || row >= 0 || column < tbUsuarios.getColumnCount() || column >= 0) {
            Object vals = tbUsuarios.getValueAt(row, column);
            if (vals instanceof UWPButton) {
                ((UWPButton) vals).doClick(); // aqui esta
                UWPButton btns = (UWPButton) vals;
                if (btns.getName().equals("btnActualizar")) {
                    ValidacionesSistema.Parametros_Usuario.setTitulo("Actualizar usuario");
                    ValidacionesSistema.Parametros_Usuario.setBoton("Actualizar");
                    FrmAgg_Usuarios ac = new FrmAgg_Usuarios(ValidacionesSistema.Parametros_Usuario.getTitulo());
                    if (ac.isVisible()) {
                        ac.toFront();

                    } else {
                        ac.setVisible(true);
                        frmstate = 1;
                    }
                   
                }
                if (btns.getName().equals("btnEliminar")) {
                    int confirmar = 0;
                    nombre = ValidacionesSistema.Parametros_Usuario.getNombre_usuario();
                    confirmar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el usuario de: " + nombre + "?", "Proceso de Eliminar", confirmar);
                    if (confirmar == 0) {
                        ControllerUsuarios obje = new ControllerUsuarios(ValidacionesSistema.Parametros_Usuario.getID());
                        boolean respuesta = obje.EliminarUsuario_C();
                        if (respuesta == true) {
                            ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso completado", "Usuario eliminado", 1);
                            CargarTabla();
                        } else {
                            ValidacionesSistema.ValidacionesBeep_Go.Notificacion("Proceso fallido", "Usuario no pudo ser eliminado", 2);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_tbUsuariosMouseClicked

    private void PanelFondoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelFondoMouseMoved
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_PanelFondoMouseMoved

    private void tbUsuariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuariosMouseMoved
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_tbUsuariosMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private javax.swing.JScrollPane PanelTabla;
    private Controles_Personalizados.ScrollBar.ScrollBarCustom ScrollTabla;
    private Controles_Personalizados.Botones.UWPButton btnAgregar;
    private Controles_Personalizados.Botones.UWPButton btnFiltrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblUsuarios;
    private Controles_Personalizados.Tables.Table tbUsuarios;
    // End of variables declaration//GEN-END:variables
}
