/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author danlo
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
        mod();
    }
    public void mode(){
        switch(ValidacionesSistema.ValidacionesBeep_Go.getModo()){
            case 1: 
                PanelFondo.setBackground(new Color(47,49,54));
                PanelGrafica1.setBackground(new Color(32,34,37));
                PanelGrafica2.setBackground(new Color(32,34,37));
                PanelGrafica3.setBackground(new Color(32,34,37));
                lblNoti.setForeground(Color.WHITE);
                PanelNotificaciones.setBackground(new Color(32,34,37)); 
                break;
            case 2:
                PanelFondo.setBackground(new Color(231,234,239));
                PanelGrafica1.setBackground(new Color(253,255,254));
                PanelGrafica2.setBackground(new Color(253,255,254));
                PanelGrafica3.setBackground(new Color(253,255,254));
                lblNoti.setForeground(Color.BLACK);
                PanelNotificaciones.setBackground(new Color(253,255,254));
                break;
                
        }
    }

    public void mod(){
        if (ValidacionesSistema.ValidacionesBeep_Go.getModo() == 1) {
            PanelFondo.setBackground(new Color(47,49,54));
            PanelGrafica1.setBackground(new Color(32,34,37));
            PanelGrafica2.setBackground(new Color(32,34,37));
            PanelGrafica3.setBackground(new Color(32,34,37));
            lblNoti.setForeground(Color.WHITE);
            PanelNotificaciones.setBackground(new Color(32,34,37)); 
        }else if(ValidacionesSistema.ValidacionesBeep_Go.getModo() == 2){
            PanelFondo.setBackground(new Color(231,234,239));
            PanelGrafica1.setBackground(new Color(253,255,254));
            PanelGrafica2.setBackground(new Color(253,255,254));
            PanelGrafica3.setBackground(new Color(253,255,254));
            lblNoti.setForeground(Color.BLACK);
            PanelNotificaciones.setBackground(new Color(253,255,254));             
        }
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new Controles_Personalizados.Paneles.PanelRound();
        pnlCenter = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        PanelGrafica1 = new Controles_Personalizados.Paneles.PanelRound();
        jPanel14 = new javax.swing.JPanel();
        PanelGrafica2 = new Controles_Personalizados.Paneles.PanelRound();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        PanelGrafica3 = new Controles_Personalizados.Paneles.PanelRound();
        jPanel11 = new javax.swing.JPanel();
        pnlEast = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        PanelNotificaciones = new Controles_Personalizados.Paneles.PanelRound();
        lblNoti = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(231, 234, 239));
        setLayout(new java.awt.BorderLayout());

        PanelFondo.setBackground(new java.awt.Color(231, 234, 239));
        PanelFondo.setLayout(new java.awt.BorderLayout());

        pnlCenter.setBackground(new java.awt.Color(231, 234, 239));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(231, 234, 239));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(231, 234, 239));
        jPanel5.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(231, 234, 239));
        jPanel13.setPreferredSize(new java.awt.Dimension(650, 100));
        jPanel13.setLayout(new java.awt.BorderLayout());

        PanelGrafica1.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica1.setPreferredSize(new java.awt.Dimension(562, 293));
        PanelGrafica1.setRoundBottomLeft(20);
        PanelGrafica1.setRoundBottomRight(20);
        PanelGrafica1.setRoundTopLeft(20);
        PanelGrafica1.setRoundTopRight(20);
        PanelGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(PanelGrafica1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13, java.awt.BorderLayout.WEST);

        jPanel14.setBackground(new java.awt.Color(231, 234, 239));
        jPanel14.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel14.setLayout(new java.awt.BorderLayout());

        PanelGrafica2.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica2.setPreferredSize(new java.awt.Dimension(361, 292));
        PanelGrafica2.setRoundBottomLeft(20);
        PanelGrafica2.setRoundBottomRight(20);
        PanelGrafica2.setRoundTopLeft(20);
        PanelGrafica2.setRoundTopRight(20);
        PanelGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(PanelGrafica2, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel14, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(231, 234, 239));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 5));
        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(231, 234, 239));
        jPanel7.setPreferredSize(new java.awt.Dimension(30, 100));
        jPanel1.add(jPanel7, java.awt.BorderLayout.WEST);

        pnlCenter.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(231, 234, 239));
        jPanel10.setPreferredSize(new java.awt.Dimension(30, 100));
        jPanel2.add(jPanel10, java.awt.BorderLayout.WEST);

        jPanel9.setBackground(new java.awt.Color(231, 234, 239));
        jPanel2.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(231, 234, 239));
        jPanel8.setLayout(new java.awt.BorderLayout());

        PanelGrafica3.setBackground(new java.awt.Color(253, 255, 254));
        PanelGrafica3.setPreferredSize(new java.awt.Dimension(938, 293));
        PanelGrafica3.setRoundBottomLeft(20);
        PanelGrafica3.setRoundBottomRight(20);
        PanelGrafica3.setRoundTopLeft(20);
        PanelGrafica3.setRoundTopRight(20);
        PanelGrafica3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(PanelGrafica3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(231, 234, 239));
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel2.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        pnlCenter.add(jPanel2, java.awt.BorderLayout.SOUTH);

        PanelFondo.add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlEast.setBackground(new java.awt.Color(231, 234, 239));
        pnlEast.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(231, 234, 239));
        jPanel16.setPreferredSize(new java.awt.Dimension(5, 100));
        pnlEast.add(jPanel16, java.awt.BorderLayout.LINE_END);

        PanelNotificaciones.setBackground(new java.awt.Color(253, 255, 254));
        PanelNotificaciones.setPreferredSize(new java.awt.Dimension(165, 602));
        PanelNotificaciones.setRoundBottomLeft(20);
        PanelNotificaciones.setRoundBottomRight(20);
        PanelNotificaciones.setRoundTopLeft(20);
        PanelNotificaciones.setRoundTopRight(20);
        PanelNotificaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoti.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblNoti.setForeground(new java.awt.Color(42, 36, 56));
        lblNoti.setText("Notificaciones");
        PanelNotificaciones.add(lblNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlEast.add(PanelNotificaciones, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(231, 234, 239));
        pnlEast.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(231, 234, 239));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 5));
        pnlEast.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel15.setBackground(new java.awt.Color(231, 234, 239));
        pnlEast.add(jPanel15, java.awt.BorderLayout.PAGE_END);

        PanelFondo.add(pnlEast, java.awt.BorderLayout.EAST);

        add(PanelFondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelFondo;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica1;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica2;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica3;
    private Controles_Personalizados.Paneles.PanelRound PanelNotificaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlEast;
    // End of variables declaration//GEN-END:variables
}
