/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author ferna
 */
public class PanelOpcionesPersonal extends javax.swing.JFrame{

    /**
     * Creates new form PanelOpcionesPersonal
     */
    public PanelOpcionesPersonal() {
        initComponents();
        Shape forma= new RoundRectangle2D.Double(0,0, this.getBounds() .width, this.getBounds() .height,40,40);
        AWTUtilities. setWindowShape(this, forma);
        setIconImage(Logo());
    }
public Image Logo(){
    Image retvalue=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
    return retvalue;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpcionesPersonal = new Controles_Personalizados.Paneles.PanelRound();
        PanelSeleccionEstudiantes = new Controles_Personalizados.Paneles.PanelRound();
        btnEstudiantes = new javax.swing.JLabel();
        btnProfesores = new javax.swing.JLabel();
        panelSeleccionProfesores = new Controles_Personalizados.Paneles.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(130, 69));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpcionesPersonal.setBackground(new java.awt.Color(58, 50, 75));
        panelOpcionesPersonal.setRoundBottomLeft(20);
        panelOpcionesPersonal.setRoundBottomRight(20);
        panelOpcionesPersonal.setRoundTopLeft(20);
        panelOpcionesPersonal.setRoundTopRight(20);
        panelOpcionesPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSeleccionEstudiantes.setBackground(new java.awt.Color(42, 36, 56));
        PanelSeleccionEstudiantes.setPreferredSize(new java.awt.Dimension(122, 67));
        PanelSeleccionEstudiantes.setRoundBottomLeft(20);
        PanelSeleccionEstudiantes.setRoundBottomRight(20);
        PanelSeleccionEstudiantes.setRoundTopLeft(20);
        PanelSeleccionEstudiantes.setRoundTopRight(20);
        PanelSeleccionEstudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-graduation 1.png"))); // NOI18N
        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstudiantesMouseClicked(evt);
            }
        });
        PanelSeleccionEstudiantes.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        panelOpcionesPersonal.add(PanelSeleccionEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/chalkboard-user-solid 1.png"))); // NOI18N
        btnProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfesoresMouseClicked(evt);
            }
        });
        panelOpcionesPersonal.add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 22, -1, -1));

        panelSeleccionProfesores.setBackground(new java.awt.Color(42, 36, 56));
        panelSeleccionProfesores.setPreferredSize(new java.awt.Dimension(122, 67));
        panelSeleccionProfesores.setRoundBottomLeft(20);
        panelSeleccionProfesores.setRoundBottomRight(20);
        panelSeleccionProfesores.setRoundTopLeft(20);
        panelSeleccionProfesores.setRoundTopRight(20);
        panelSeleccionProfesores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelOpcionesPersonal.add(panelSeleccionProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, 50));

        getContentPane().add(panelOpcionesPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static int showinter=0;

    public static int getShowinter() {
        return showinter;
    }    
    
    private void btnEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstudiantesMouseClicked
        PanelOpcionesPersonal.showinter = 1;
        this.dispose();
        
    }//GEN-LAST:event_btnEstudiantesMouseClicked

    private void btnProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfesoresMouseClicked
        PanelOpcionesPersonal.showinter = 2;
        this.dispose();
        
    }//GEN-LAST:event_btnProfesoresMouseClicked
    void closePanel(){
        this.dispose();
        PanelOpcionesPersonal.showinter = 0;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelOpcionesPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelOpcionesPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelOpcionesPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelOpcionesPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelOpcionesPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelSeleccionEstudiantes;
    private javax.swing.JLabel btnEstudiantes;
    private javax.swing.JLabel btnProfesores;
    private Controles_Personalizados.Paneles.PanelRound panelOpcionesPersonal;
    private Controles_Personalizados.Paneles.PanelRound panelSeleccionProfesores;
    // End of variables declaration//GEN-END:variables


}
