/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author danlo
 */
public class Prueba extends javax.swing.JDialog {

    /**
     * Creates new form Prueba
     */
    public Prueba(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new Controles_Personalizados.Paneles.PanelRound();
        txtBuscar = new Controles_Personalizados.BarraBusqueda.TextFieldAnimation();
        PanelFecha = new Controles_Personalizados.Paneles.PanelRound();
        lblHora = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblSun = new javax.swing.JLabel();
        PanelMO = new Controles_Personalizados.Paneles.PanelRound();
        lblNormal = new javax.swing.JLabel();
        btnMO = new javax.swing.JLabel();
        PanelDatosUs = new Controles_Personalizados.Paneles.PanelRound();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblUsuarioDark = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        PanelGrafica1 = new Controles_Personalizados.Paneles.PanelRound();
        PanelGrafica2 = new Controles_Personalizados.Paneles.PanelRound();
        PanelGrafica3 = new Controles_Personalizados.Paneles.PanelRound();
        PanelNotificaciones = new Controles_Personalizados.Paneles.PanelRound();
        lblNoti = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btnMinimizar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(32, 34, 37));

        PanelContenedor.setBackground(new java.awt.Color(231, 234, 239));
        PanelContenedor.setPreferredSize(new java.awt.Dimension(1155, 729));
        PanelContenedor.setRoundBottomLeft(30);
        PanelContenedor.setRoundBottomRight(30);
        PanelContenedor.setRoundTopLeft(30);
        PanelContenedor.setRoundTopRight(30);
        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(253, 255, 254));
        txtBuscar.setForeground(new java.awt.Color(42, 36, 56));
        txtBuscar.setAnimationColor(new java.awt.Color(42, 36, 56));
        txtBuscar.setHintText("Buscar");
        txtBuscar.setPreferredSize(new java.awt.Dimension(712, 52));
        txtBuscar.setSelectionColor(new java.awt.Color(42, 36, 56));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        PanelContenedor.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 690, 50));

        PanelFecha.setBackground(new java.awt.Color(253, 255, 254));
        PanelFecha.setPreferredSize(new java.awt.Dimension(152, 52));
        PanelFecha.setRoundBottomLeft(20);
        PanelFecha.setRoundBottomRight(20);
        PanelFecha.setRoundTopLeft(20);
        PanelFecha.setRoundTopRight(20);
        PanelFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHora.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(42, 36, 56));
        lblHora.setText("7:00 am");
        PanelFecha.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblDia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(42, 36, 56));
        lblDia.setText("THU");
        PanelFecha.add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblSun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-sun.png"))); // NOI18N
        PanelFecha.add(lblSun, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -2, -1, 60));

        PanelContenedor.add(PanelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 160, 60));

        PanelMO.setBackground(new java.awt.Color(253, 255, 254));
        PanelMO.setPreferredSize(new java.awt.Dimension(57, 54));
        PanelMO.setRoundBottomLeft(20);
        PanelMO.setRoundBottomRight(20);
        PanelMO.setRoundTopLeft(20);
        PanelMO.setRoundTopRight(20);
        PanelMO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/lblNormal.png"))); // NOI18N
        lblNormal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNormalMouseClicked(evt);
            }
        });
        PanelMO.add(lblNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        btnMO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-moon.png"))); // NOI18N
        btnMO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMOMouseClicked(evt);
            }
        });
        PanelMO.add(btnMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        PanelContenedor.add(PanelMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 70, 60));

        PanelDatosUs.setBackground(new java.awt.Color(253, 255, 254));
        PanelDatosUs.setPreferredSize(new java.awt.Dimension(174, 55));
        PanelDatosUs.setRoundBottomLeft(20);
        PanelDatosUs.setRoundBottomRight(20);
        PanelDatosUs.setRoundTopLeft(20);
        PanelDatosUs.setRoundTopRight(20);
        PanelDatosUs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(42, 36, 56));
        lblNombre.setText("Daniel L.");
        PanelDatosUs.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 7, -1, 30));

        lblTipo.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(42, 36, 56));
        lblTipo.setText("Administrador");
        PanelDatosUs.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        lblUsuarioDark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/usuario-blanco.png"))); // NOI18N
        PanelDatosUs.add(lblUsuarioDark, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 60));

        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-user-circle.png"))); // NOI18N
        PanelDatosUs.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 40, 60));

        PanelContenedor.add(PanelDatosUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 30, -1, 60));

        PanelGrafica1.setBackground(new java.awt.Color(32, 34, 37));
        PanelGrafica1.setPreferredSize(new java.awt.Dimension(562, 293));
        PanelGrafica1.setRoundBottomLeft(20);
        PanelGrafica1.setRoundBottomRight(20);
        PanelGrafica1.setRoundTopLeft(20);
        PanelGrafica1.setRoundTopRight(20);
        PanelGrafica1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelContenedor.add(PanelGrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, 570, 310));

        PanelGrafica2.setBackground(new java.awt.Color(42, 45, 49));
        PanelGrafica2.setPreferredSize(new java.awt.Dimension(361, 292));
        PanelGrafica2.setRoundBottomLeft(20);
        PanelGrafica2.setRoundBottomRight(20);
        PanelGrafica2.setRoundTopLeft(20);
        PanelGrafica2.setRoundTopRight(20);
        PanelGrafica2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelContenedor.add(PanelGrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 102, -1, 310));

        PanelGrafica3.setBackground(new java.awt.Color(47, 49, 54));
        PanelGrafica3.setPreferredSize(new java.awt.Dimension(938, 293));
        PanelGrafica3.setRoundBottomLeft(20);
        PanelGrafica3.setRoundBottomRight(20);
        PanelGrafica3.setRoundTopLeft(20);
        PanelGrafica3.setRoundTopRight(20);
        PanelGrafica3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelContenedor.add(PanelGrafica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 940, -1));

        PanelNotificaciones.setBackground(new java.awt.Color(253, 255, 254));
        PanelNotificaciones.setPreferredSize(new java.awt.Dimension(165, 602));
        PanelNotificaciones.setRoundBottomLeft(20);
        PanelNotificaciones.setRoundBottomRight(20);
        PanelNotificaciones.setRoundTopLeft(20);
        PanelNotificaciones.setRoundTopRight(20);
        PanelNotificaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoti.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblNoti.setForeground(new java.awt.Color(42, 36, 56));
        lblNoti.setText("Notificaciones");
        PanelNotificaciones.add(lblNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelContenedor.add(PanelNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 102, 180, 610));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/MinimizarLogin.png"))); // NOI18N
        PanelContenedor.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        PanelContenedor.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, -1, -1));

        btnMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/MinimizarLogin.png"))); // NOI18N
        PanelContenedor.add(btnMinimizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1155, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void lblNormalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNormalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNormalMouseClicked

    private void btnMOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMOMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMOMouseClicked

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prueba dialog = new Prueba(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Paneles.PanelRound PanelContenedor;
    private Controles_Personalizados.Paneles.PanelRound PanelDatosUs;
    private Controles_Personalizados.Paneles.PanelRound PanelFecha;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica1;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica2;
    private Controles_Personalizados.Paneles.PanelRound PanelGrafica3;
    private Controles_Personalizados.Paneles.PanelRound PanelMO;
    private Controles_Personalizados.Paneles.PanelRound PanelNotificaciones;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JLabel btnMO;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel btnMinimizar1;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNormal;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JLabel lblSun;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioDark;
    private Controles_Personalizados.BarraBusqueda.TextFieldAnimation txtBuscar;
    // End of variables declaration//GEN-END:variables
}
