/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControllerQR;
import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import java.io.ByteArrayOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author danlo
 */
public class RecuQR extends javax.swing.JFrame {

    private String usuario;
    private String Carne;
    ControllerQR objControllerQR = new ControllerQR();
    String numero;

    /**
     * Creates new form RecuperacionQR
     */
    public RecuQR() {
        initComponents();
        this.setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 40, 40);
        AWTUtilities.setWindowShape(this, forma);
        setIconImage(Logo());
    }

    public Image Logo() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Recursos_Proyecto/B&G Morado 2.png"));
        return retvalue;
    }

    void CapCarnet() {
        objControllerQR.setUsuario(TxtUsuario.getText());
        ResultSet rs = objControllerQR.RecuperarContraQR();
        try {
            if (rs.next()) {
                usuario = rs.getString("nombre_usuario");
                Carne = rs.getString("Carnet");
            }
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }

    public void generarQR() {
        ImageIcon FondoQR = new ImageIcon(getClass().getResource("/Recursos_Proyecto/Rectangle 1.png"));
        LblQr.setIcon(FondoQR);
        CapCarnet();
        System.out.println(usuario);
        if (!TxtUsuario.getText().equals(usuario)) {
            JOptionPane.showMessageDialog(null, "Verificar, el usuario, no se encontro ningun usuario con ese nombre", "Usuario Inexistente", JOptionPane.WARNING_MESSAGE);
            TxtUsuario.setText("");
        } else {
            try {
                int min = 1000;
                int max = 9999;
                Random random = new Random();
                int valornum = random.nextInt(max + min) + min;
                numero = String.valueOf(valornum);
                ByteArrayOutputStream out = QRCode.from(numero).to(ImageType.PNG).stream();
                ImageIcon imagenqr = new ImageIcon(out.toByteArray());
                LblQr.setIcon(imagenqr);
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new Controles_Personalizados.Paneles.PanelRound();
        PanelContenedorCampos = new Controles_Personalizados.Paneles.PanelRound();
        btnGoBack = new javax.swing.JLabel();
        textoRest = new javax.swing.JLabel();
        TxtUsuario = new Controles_Personalizados.textfields.TextField();
        btnGenerar = new Controles_Personalizados.Botones.ButtonGradient();
        ContenedorCodigoQR = new Controles_Personalizados.Paneles.PanelRound();
        LblQr = new rojerusan.RSLabelImage();
        TxtNumeroCifrado = new Controles_Personalizados.textfields.TextField();
        BtnValidarNum = new Controles_Personalizados.Botones.ButtonGradient();
        ImagenRecuQR = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedor.setBackground(new java.awt.Color(42, 36, 56));
        PanelContenedor.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelContenedor.setRoundBottomLeft(40);
        PanelContenedor.setRoundBottomRight(40);
        PanelContenedor.setRoundTopLeft(40);
        PanelContenedor.setRoundTopRight(40);
        PanelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedorCampos.setBackground(new java.awt.Color(254, 254, 254));
        PanelContenedorCampos.setPreferredSize(new java.awt.Dimension(698, 768));
        PanelContenedorCampos.setRoundBottomLeft(35);
        PanelContenedorCampos.setRoundTopLeft(35);
        PanelContenedorCampos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/bxs-left-arrow-circle 1.png"))); // NOI18N
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBackMouseClicked(evt);
            }
        });
        PanelContenedorCampos.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textoRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/txtRecuQR.png"))); // NOI18N
        PanelContenedorCampos.add(textoRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));
        TxtUsuario.setBackground(new java.awt.Color(254, 254, 254));
        TxtUsuario.setForeground(new java.awt.Color(42, 36, 56));
        TxtUsuario.setCaretColor(new java.awt.Color(42, 36, 56));
        TxtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        TxtUsuario.setLabelText("Usuario");
        TxtUsuario.setLineColor(new java.awt.Color(42, 36, 56));
        TxtUsuario.setSelectionColor(new java.awt.Color(58, 50, 75));
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });
        PanelContenedorCampos.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 310, 70));

        btnGenerar.setText("Generar Código");
        btnGenerar.setToolTipText("");
        btnGenerar.setColor1(new java.awt.Color(42, 36, 56));
        btnGenerar.setColor2(new java.awt.Color(42, 36, 56));
        btnGenerar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        PanelContenedorCampos.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 310, -1));

        ContenedorCodigoQR.setBackground(new java.awt.Color(42, 36, 56));
        ContenedorCodigoQR.setPreferredSize(new java.awt.Dimension(259, 252));
        ContenedorCodigoQR.setRoundBottomLeft(40);
        ContenedorCodigoQR.setRoundBottomRight(40);
        ContenedorCodigoQR.setRoundTopLeft(40);
        ContenedorCodigoQR.setRoundTopRight(40);
        ContenedorCodigoQR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblQr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Rectangle 1.png"))); // NOI18N
        ContenedorCodigoQR.add(LblQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 210));

        PanelContenedorCampos.add(ContenedorCodigoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, -1, -1));
        ContenedorCodigoQR.add(LblQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 180));

        PanelContenedorCampos.add(ContenedorCodigoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 220, 220));

        TxtNumeroCifrado.setBackground(new java.awt.Color(254, 254, 254));
        TxtNumeroCifrado.setCaretColor(new java.awt.Color(42, 36, 56));
        TxtNumeroCifrado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TxtNumeroCifrado.setLabelText("Número Cifrado");
        TxtNumeroCifrado.setLineColor(new java.awt.Color(42, 36, 56));
        TxtNumeroCifrado.setSelectionColor(new java.awt.Color(58, 50, 75));
        TxtNumeroCifrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNumeroCifradoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNumeroCifradoKeyTyped(evt);
            }
        });
        PanelContenedorCampos.add(TxtNumeroCifrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 310, 70));

        BtnValidarNum.setText("Validar Número");
        BtnValidarNum.setColor1(new java.awt.Color(58, 50, 75));
        BtnValidarNum.setColor2(new java.awt.Color(58, 50, 75));
        BtnValidarNum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BtnValidarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnValidarNumActionPerformed(evt);
            }
        });
        PanelContenedorCampos.add(BtnValidarNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 475, 310, 44));
        PanelContenedor.add(PanelContenedorCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ImagenRecuQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/QRimg.png"))); // NOI18N
        PanelContenedor.add(ImagenRecuQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/Maximizar.png"))); // NOI18N
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        PanelContenedor.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos_Proyecto/CerrarLogin.png"))); // NOI18N
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarMousePressed(evt);
            }
        });
        PanelContenedor.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 20, -1, -1));

        getContentPane().add(PanelContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseClicked
        // TODO add your handling code here:
        MenuRecu men = new MenuRecu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGoBackMouseClicked

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        //CapCarnet();
        generarQR();
//        FrmRestablecimiento fr = new FrmRestablecimiento();
//        fr.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMousePressed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMouseClicked

    void Proceso() {
        if (TxtNumeroCifrado.getText().equals(numero)) {
            String clave = TxtUsuario.getText() + "123";
            objControllerQR.setClave(ValidacionesSistema.ValidacionesBeep_Go.EncriptarContra(clave));
            objControllerQR.setUsuario(TxtUsuario.getText());
            if (objControllerQR.ActualizarcontraQR()) {
                JOptionPane.showMessageDialog(null, "Su usuario a sido reestablecido a su usuario + 123", "Contraseña Reestablecida", JOptionPane.INFORMATION_MESSAGE);
                FrmLogin log = new FrmLogin();
                log.setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "El número ingresado, no es valido", "Números Incorrectos", JOptionPane.WARNING_MESSAGE);
            TxtNumeroCifrado.setText("");
        }
    }

    private void BtnValidarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnValidarNumActionPerformed
        // TODO add your handling code here:
        Proceso();
    }//GEN-LAST:event_BtnValidarNumActionPerformed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (TxtUsuario.getText().length() >= 15) {
            evt.consume();
        } else {
            if (TxtUsuario.getText().equals("") && car == 95) {
                evt.consume();
            } else if (TxtUsuario.getText().contains("_") && car == 95) {
                evt.consume();
            } else {
                ValidacionesSistema.ValidacionesBeep_Go.SinEspacios(evt);
                ValidacionesSistema.ValidacionesBeep_Go.SoloLetrasNumerosGuionBajo(evt);
            }
        }
    }//GEN-LAST:event_TxtUsuarioKeyTyped

    private void TxtNumeroCifradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroCifradoKeyTyped
        // TODO add your handling code here:
        if (TxtNumeroCifrado.getText().length() >= 5) {
            evt.consume();
        } else {
            ValidacionesSistema.ValidacionesBeep_Go.SoloNumeros(evt);
        }
    }//GEN-LAST:event_TxtNumeroCifradoKeyTyped

    private void TxtNumeroCifradoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNumeroCifradoKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && TxtNumeroCifrado.getText() != "" && TxtUsuario.getText() != "") {
            Proceso();
        }
    }//GEN-LAST:event_TxtNumeroCifradoKeyPressed

    private void TxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER && TxtUsuario.getText() != "") {
            generarQR();
        }
    }//GEN-LAST:event_TxtUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuQR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Controles_Personalizados.Botones.ButtonGradient BtnValidarNum;
    private Controles_Personalizados.Paneles.PanelRound ContenedorCodigoQR;
    private javax.swing.JLabel ImagenRecuQR;
    private rojerusan.RSLabelImage LblQr;
    private Controles_Personalizados.Paneles.PanelRound PanelContenedor;
    private Controles_Personalizados.Paneles.PanelRound PanelContenedorCampos;
    private Controles_Personalizados.textfields.TextField TxtNumeroCifrado;
    private Controles_Personalizados.textfields.TextField TxtUsuario;
    private javax.swing.JLabel btnCerrar;
    private Controles_Personalizados.Botones.ButtonGradient btnGenerar;
    private javax.swing.JLabel btnGoBack;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JLabel textoRest;
    // End of variables declaration//GEN-END:variables
}
